#!/bin/bash




#############################################################################
# Functions for compiling and cleaning up compiled binaries
BINARIES="fppd fpp fppmm"
cleanCompiledBinaries() {
    echo "in Clean stage"

	if [ "x${FPPDIR}" = "x/opt/fpp" ]; then
		cd ${FPPDIR}/src && ${SUDO} make clean
	else
		cd ${FPPDIR}/src && sudo -u ${FPPUSER} make clean
	fi

    for p in ${MEDIADIR}/plugins/*; do
        if [ -d "$p" ]; then
            if [ -f "${p}/Makefile" ]; then
                echo "Cleaning plugin $p"
                if [ "x${FPPDIR}" = "x/opt/fpp" ]; then
                    ${SUDO} make -C "${p}" -f "${p}/Makefile" SRCDIR=${FPPDIR}/src clean
                else
                    sudo -u ${FPPUSER} make -C "${p}" -f "${p}/Makefile" SRCDIR=${FPPDIR}/src clean
                fi
            fi
        fi
    done
}
populateCCACHE() {
    FPPBASEVERSION=$(</etc/fpp/rfs_version)
    FPPPLATFORM=$(cat /etc/fpp/platform 2> /dev/null)
    MAJVER=${FPPBASEVERSION:1:1}
    if [[ ${MAJVER} -eq 2 ]]; then
        MAJVER=${FPPBASEVERSION:1:4}
        MINVER=${FPPBASEVERSION:6:2}
    else
        MINVER=${FPPBASEVERSION:3:2}
        if [[ $MINVER == *"-" ]]; then
            MINVER=${FPPBASEVERSION:3:1}
        fi
    fi
    if  [ "${FPPPLATFORM}" = "Raspberry Pi" ]; then
        PLAT=Pi
    elif [ "${FPPPLATFORM}" = "BeagleBone Black" ]; then
        PLAT=BBB
    elif [ "${FPPPLATFORM}" = "BeagleBone 64" ]; then
        PLAT=BB64
    else
        echo "populateCache stopping, Unknown platform - ${FPPPLATFORM}"
        MAJVER=0
        MINVER=0
    fi
    if [[ ${MAJVER} -gt 3 || ${MAJVER} -eq 3 && ${MINVER} -ge 3 ]]; then
        #at least v3.3
        BRANCH=$(sudo git branch --list | grep \* | colrm 1 2)

        FILETOGET="ccache-${PLAT}-${MAJVER}.x-${BRANCH}.tar.gz"
        FULLURL="https://falconchristmas.github.io/ccache/${FILETOGET}"
        ETAG_GIT="/tmp/etag.$$"
        ETAG_LOCAL="/root/.ccache/etag"
        NEEDS_UPDATED=0

        echo "Checking CCACHE -  $FILETOGET - $FULLURL"

        sudo test -f "$ETAG_LOCAL"
        ETAG_LOCAL_NOTFOUND=$?

        curl -I $FULLURL | grep -i etag > $ETAG_GIT

        ETAG_SIZE=$(wc -c $ETAG_GIT | awk '{print $1}')

        if (($ETAG_SIZE < 5)); then
            echo "Updating CCache -- Invalid etag"
            NEEDS_UPDATED=1
        elif [ "$ETAG_LOCAL_NOTFOUND" == "1" ] ; then
            echo "Updating CCache -- not cached"
            NEEDS_UPDATED=1
        else
            sudo diff -q $ETAG_LOCAL $ETAG_GIT
            rc=$?
            if [ $rc -ne "0" ]; then
                echo "Updating CCache - eTag has changed"
                NEEDS_UPDATED=1
            fi
        fi

        if [ $NEEDS_UPDATED -eq "0" ]; then
            echo "CCache is up to date"
            rm "$ETAG_GIT" # cleanup
            return 0
        fi


        curl  -f --fail-early $FULLURL --output "/tmp/$FILETOGET"

        if [ -f "/tmp/$FILETOGET" ]; then
            sudo cp /root/.ccache/ccache.conf /tmp
            sudo tar -x -z -C /root -f "/tmp/$FILETOGET"
            rm -f "/tmp/$FILETOGET"
            sudo mv $ETAG_GIT $ETAG_LOCAL
            sudo chmod 644 $ETAG_LOCAL
            sudo cp /tmp/ccache.conf /root/.ccache/ccache.conf
        fi
    fi

    # set the CCache sizes/flags that we need to be able to successfully compile
    sudo ccache -M 500M
    sudo ccache --set-config=temporary_dir=/tmp
    sudo ccache --set-config=sloppiness=pch_defines,time_macros,include_file_mtime,include_file_ctime,locale,modules
    sudo ccache --set-config=pch_external_checksum=true
    sudo ccache --set-config=hard_link=true
    # See FPP_Install.sh for rationale -- mtime-based compiler check
    # invalidates the entire image-build cache after any harmless touch
    # of /usr/bin/g++.
    sudo ccache --set-config=compiler_check=content
}


function ComputeMakeParallelism() {
    local CPUS=1
    if [ -f "/proc/cpuinfo" ]; then
        CPUS=$(grep "^processor" /proc/cpuinfo | wc -l)

        if [[ ${CPUS} -gt 1 ]]; then
            MEMORY=$(grep MemTot /proc/meminfo | awk '{print $2}')
            ARMV=$(uname -m)
            if [[ ${MEMORY} -lt 425000 ]]; then
                # very limited memory, only use one core or we'll fail or
                # will be very slow as we constantly swap in/out
                CPUS=1
            elif [[ ${MEMORY} -lt 512000 ]]; then
                if [ "$ARMV" = "aarch64" ]; then
                    # 64bit compiles take more memory so if we are less than 512M, 
                    # we need to stick with a single core or it will swap
                    CPUS=1
                else
                    SWAPTOTAL=$(grep SwapTotal /proc/meminfo | awk '{print $2}')
                    # Limited memory, if we have some swap, we'll go ahead with -j 2
                    # otherwise we'll need to stick with -j 1 or we run out of memory
                    if [[ ${SWAPTOTAL} -gt 49000 ]]; then
                        CPUS=2
                    else
                        CPUS=1
                    fi
                fi
            elif [[ ${MEMORY} -lt 1000000 ]]; then
                if [[ ${CPUS} -gt 3 ]]; then
                    CPUS=3
                fi
            fi
        fi
    else
        CPUS=$(sysctl -n hw.ncpu)
    fi
    echo "$CPUS"
}

compileBinaries() {

    cleanCompiledBinaries
    if [ "${FPPPLATFORM}" != "MacOS" ]; then
        populateCCACHE
    fi

    # export CCACHE_LOGFILE=/tmp/cache.debug
    export LANG=en_US.UTF-8
    export TERM=linux

    CPUS=$(ComputeMakeParallelism)

    # Need to unset HOME so that ccache will user /root instead of /home/fpp
    unset HOME

    if [ "${FPPPLATFORM}" != "MacOS" ]; then
        MEMORY=$(grep MemTot /proc/meminfo | awk '{print $2}')
        FPPDPID=$(pgrep fppd)
        if [ ${MEMORY} -lt 512000 -a "${FPPDPID}" != "" ]; then
            SWAPTOTAL=$(grep SwapTotal /proc/meminfo | awk '{print $2}')
            
            if [ ${SWAPTOTAL} -lt 384000 ]; then
                echo "System has less than 512MB RAM and little swap, activating more swap."
                # Create swapfile in fpp media so it will go onto the
                # storage location most likely having space on it (not
                # eMMC on Beagles)
                #
                # some of the larger C++ files are consuming a lot of memory
                # and are starting to cause compile failures on the devices
                # with limitted memory (PiZeros, older Pi's, etc...) so
                # we'll allocate a swap file so it shouldn't fail, but
                # will likely be slow.   We DON'T want an "always" swapfile
                # to avoid killing the SD cards.
                ${SUDO} fallocate -l 384M "${FPPHOME}/media/tmp/swapfile"
                ${SUDO} chmod 600 "${FPPHOME}/media/tmp/swapfile"
                ${SUDO} mkswap -q "${FPPHOME}/media/tmp/swapfile"
                ${SUDO} swapon "${FPPHOME}/media/tmp/swapfile"
            fi
        fi
    fi

	if [ "x${FPPDIR}" = "x/opt/fpp" ]; then
		cd ${FPPDIR}/src && ${SUDO} make clean && ${SUDO} -E make -j ${CPUS} optimized
	else
		cd ${FPPDIR}/src && sudo -u ${FPPUSER} make clean && sudo -u ${FPPUSER} make -j ${CPUS} optimized
	fi

    for p in ${MEDIADIR}/plugins/*; do
        if [ -d "$p" ]; then
            if [ -f "${p}/Makefile" ]; then
                echo "Building plugin $p"
                if [ "x${FPPDIR}" = "x/opt/fpp" ]; then
                    ${SUDO} make -C "${p}" -f "${p}/Makefile" -j ${CPUS} SRCDIR=${FPPDIR}/src
                    ${SUDO} chown -R ${FPPUSER}:${FPPGROUP} "${p}"
                else
                    sudo -u ${FPPUSER} make -C "${p}" -f "${p}/Makefile" -j ${CPUS} SRCDIR=${FPPDIR}/src
                fi
            fi
        fi
    done

    if [ "${FPPPLATFORM}" != "MacOS" ]; then    
        if [ -f "${FPPHOME}/media/tmp/swapfile" ]; then
            #remove the swap that was created
            ${SUDO} swapoff "${FPPHOME}/media/tmp/swapfile"
            ${SUDO} rm -f "${FPPHOME}/media/tmp/swapfile"
        fi
    fi
}

#############################################################################
# Helper script for running the User hook script with a specified hook
runUserHookScript() {
	if [ -f "${MEDIADIR}/scripts/UserCallbackHook.sh" ]
	then
		/bin/bash ${MEDIADIR}/scripts/UserCallbackHook.sh $1
	fi
}
# These are normally run from fppd_start and fppd_stop
runPreStartScripts() {
	runUserHookScript preStart

	/bin/ls -1 ${PLUGINDIR}/*/scripts/preStart.sh 2> /dev/null | while read FILE
	do
		echo "Running: ${FILE}"
		/bin/bash ${FILE}
	done
}

runPostStartScripts() {
	/bin/ls -1 ${PLUGINDIR}/*/scripts/postStart.sh 2> /dev/null | while read FILE
	do
		echo "Running: ${FILE}"
		/bin/bash ${FILE}
	done

	runUserHookScript postStart
}

runPreStopScripts() {
	runUserHookScript preStop

	/bin/ls -1 ${PLUGINDIR}/*/scripts/preStop.sh 2> /dev/null | while read FILE
	do
		echo "Running: ${FILE}"
		/bin/bash ${FILE}
	done
}

runPostStopScripts() {
	/bin/ls -1 ${PLUGINDIR}/*/scripts/postStop.sh 2> /dev/null | while read FILE
	do
		echo "Running: ${FILE}"
		/bin/bash ${FILE}
	done

	runUserHookScript postStop
}


#############################################################################
# Handle calling a function directly
#
# Example: /opt/fpp/scripts/functions runPreStartScripts
BASENAME=$(basename -- $0)
if [ "${BASENAME}" = "functions" -a -n "$1" ]
then
    $@
fi

